export const SET_WALLET = 'SET_WALLET';
export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILED = 'GET_BALANCE_FAILED';
export const MAKE_TRANSACTION_REQUEST = 'MAKE_TRANSACTION_REQUEST';
